# Grid Search CV

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = sns.load_dataset('iris')

In [4]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X = df.drop('species', axis=1)
y = df['species']

In [8]:
# with train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
from sklearn.neighbors import KNeighborsClassifier

In [10]:
model_knn = KNeighborsClassifier(n_neighbors=5)
model_knn.fit(X_train, y_train)

KNeighborsClassifier()

In [11]:
model_knn.score(X_test, y_test)

1.0

In [12]:
from sklearn.svm import SVC

In [13]:
# model_svm = SVC(C = 30, kernel = 'rbf', gamma='auto')
model_svm = SVC(gamma='auto')
model_svm.fit(X_train, y_train)

SVC(gamma='auto')

In [14]:
model_svm.score(X_test, y_test)

1.0

# Now lets use Grid Search CV

In [15]:
# Now lets use Grid Search CV

from sklearn.model_selection import GridSearchCV

In [16]:
classifier = GridSearchCV(model_svm, {
    'C': [1, 10, 20, 30],
    'kernel': ['rbf', 'linear', 'poly', 'sigmoid']
}, cv = 5, return_train_score = False)

In [17]:
classifier.fit(X, y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30],
                         'kernel': ['rbf', 'linear', 'poly', 'sigmoid']})

In [18]:
print("Best parameters for KNN:", classifier.best_params_)
print("Best score for KNN:", classifier.best_score_)

Best parameters for KNN: {'C': 1, 'kernel': 'rbf'}
Best score for KNN: 0.9800000000000001

In [19]:
results = pd.DataFrame(classifier.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.016802,0.008233,0.015124,0.008307,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.014052,0.002567,0.007867,0.003736,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.021299,0.012863,0.007040,0.003204,1,poly,"{'C': 1, 'kernel': 'poly'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
3,0.010212,0.008712,0.004138,0.003213,1,sigmoid,"{'C': 1, 'kernel': 'sigmoid'}",0.333333,0.100000,0.000000,0.033333,0.0,0.093333,0.125433,13
4,0.005552,0.002967,0.003446,0.001457,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
5,0.002912,0.000152,0.002246,0.000148,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,4
6,0.014072,0.014992,0.003194,0.001880,10,poly,"{'C': 10, 'kernel': 'poly'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
7,0.013158,0.002642,0.008751,0.006283,10,sigmoid,"{'C': 10, 'kernel': 'sigmoid'}",0.333333,0.100000,0.000000,0.033333,0.0,0.093333,0.125433,13
8,0.007085,0.001072,0.005756,0.001942,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,5
9,0.010969,0.004623,0.007894,0.002443,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
10,0.052657,0.037209,0.010747,0.002660,20,poly,"{'C': 20, 'kernel': 'poly'}",0.966667,0.966667,0.900000,0.933333,1.0,0.953333,0.033993,11
11,0.006533,0.001697,0.002795,0.000127,20,sigmoid,"{'C': 20, 'kernel': 'sigmoid'}",0.333333,0.100000,0.000000,0.033333,0.0,0.093333,0.125433,13
12,0.004415,0.000753,0.004234,0.002670,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.933333,1.0,0.960000,0.038873,9
13,0.005085,0.002239,0.004482,0.002819,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,9
14,0.034265,0.016540,0.004989,0.002068,30,poly,"{'C': 30, 'kernel': 'poly'}",0.966667,0.966667,0.900000,0.933333,1.0,0.953333,0.033993,11
15,0.008869,0.003515,0.004813,0.001717,30,sigmoid,"{'C': 30, 'kernel': 'sigmoid'}",0.333333,0.100000,0.000000,0.033333,0.0,0.093333,0.125433,13

In [20]:
results.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.016802,0.008233,0.015124,0.008307,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.014052,0.002567,0.007867,0.003736,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.021299,0.012863,0.007040,0.003204,1,poly,"{'C': 1, 'kernel': 'poly'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
3,0.010212,0.008712,0.004138,0.003213,1,sigmoid,"{'C': 1, 'kernel': 'sigmoid'}",0.333333,0.1,0.000000,0.033333,0.0,0.093333,0.125433,13
4,0.005552,0.002967,0.003446,0.001457,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1

In [21]:
results[['param_C', 'param_kernel', 'mean_test_score']]

    param_C param_kernel  mean_test_score
0         1          rbf         0.980000
1         1       linear         0.980000
2         1         poly         0.966667
3         1      sigmoid         0.093333
4        10          rbf         0.980000
5        10       linear         0.973333
6        10         poly         0.966667
7        10      sigmoid         0.093333
8        20          rbf         0.966667
9        20       linear         0.966667
10       20         poly         0.953333
11       20      sigmoid         0.093333
12       30          rbf         0.960000
13       30       linear         0.960000
14       30         poly         0.953333
15       30      sigmoid         0.093333

# Random Search CV

In [31]:
# Random Search CV

from sklearn.model_selection import RandomizedSearchCV

In [32]:
classifier_random = RandomizedSearchCV(model_svm, {
    'C': [1, 10, 20, 30],
    'kernel': ['rbf', 'linear', 'poly', 'sigmoid']
}, n_iter=20, cv = 5, return_train_score = False)

In [33]:
classifier_random.fit(X, y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=20,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear', 'poly',
                                                   'sigmoid']})

In [34]:
print("Best parameters for KNN:", classifier_random.best_params_)
print("Best score for KNN:", classifier_random.best_score_)

Best parameters for KNN: {'kernel': 'rbf', 'C': 1}
Best score for KNN: 0.9800000000000001

In [35]:
results_r = pd.DataFrame(classifier_random.cv_results_)
results_r

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002564,0.000669,0.001864,0.000515,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002066,0.000075,0.001610,0.000084,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.003488,0.001293,0.001710,0.000266,poly,1,"{'kernel': 'poly', 'C': 1}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
3,0.003227,0.000298,0.001953,0.000265,sigmoid,1,"{'kernel': 'sigmoid', 'C': 1}",0.333333,0.100000,0.000000,0.033333,0.0,0.093333,0.125433,13
4,0.002195,0.000197,0.001688,0.000197,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
5,0.002034,0.000162,0.001573,0.000067,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,4
6,0.005219,0.002668,0.001523,0.000022,poly,10,"{'kernel': 'poly', 'C': 10}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
7,0.003013,0.000051,0.001730,0.000043,sigmoid,10,"{'kernel': 'sigmoid', 'C': 10}",0.333333,0.100000,0.000000,0.033333,0.0,0.093333,0.125433,13
8,0.002161,0.000154,0.001649,0.000106,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,5
9,0.001981,0.000041,0.001524,0.000025,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
10,0.009036,0.006819,0.001681,0.000217,poly,20,"{'kernel': 'poly', 'C': 20}",0.966667,0.966667,0.900000,0.933333,1.0,0.953333,0.033993,11
11,0.003389,0.000536,0.002054,0.000376,sigmoid,20,"{'kernel': 'sigmoid', 'C': 20}",0.333333,0.100000,0.000000,0.033333,0.0,0.093333,0.125433,13
12,0.002061,0.000047,0.001551,0.000040,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.966667,1.000000,0.900000,0.933333,1.0,0.960000,0.038873,9
13,0.002198,0.000295,0.001737,0.000209,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,9
14,0.010283,0.006805,0.001724,0.000233,poly,30,"{'kernel': 'poly', 'C': 30}",0.966667,0.966667,0.900000,0.933333,1.0,0.953333,0.033993,11
15,0.004274,0.001038,0.002473,0.000450,sigmoid,30,"{'kernel': 'sigmoid', 'C': 30}",0.333333,0.100000,0.000000,0.033333,0.0,0.093333,0.125433,13

In [36]:
results_r[['param_C', 'param_kernel', 'mean_test_score']]

    param_C param_kernel  mean_test_score
0         1          rbf         0.980000
1         1       linear         0.980000
2         1         poly         0.966667
3         1      sigmoid         0.093333
4        10          rbf         0.980000
5        10       linear         0.973333
6        10         poly         0.966667
7        10      sigmoid         0.093333
8        20          rbf         0.966667
9        20       linear         0.966667
10       20         poly         0.953333
11       20      sigmoid         0.093333
12       30          rbf         0.960000
13       30       linear         0.960000
14       30         poly         0.953333
15       30      sigmoid         0.093333